## Import Library

In [ ]:
import pandas as pd
import uuid

In [3]:
df = pd.read_parquet('fhvhv_tripdata_2024-09.parquet')

In [4]:
df.head()

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,...,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag
0,HV0003,B03404,B03404,2024-09-01 00:00:42,2024-09-01 00:04:11,2024-09-01 00:04:54,2024-09-01 00:12:03,263,75,1.64,...,0.75,0.75,0.0,0.00,6.40,Y,N,N,N,N
1,HV0003,B03404,B03404,2024-09-01 00:26:16,2024-09-01 00:27:03,2024-09-01 00:27:49,2024-09-01 00:48:40,263,249,5.66,...,4.04,2.75,0.0,0.00,29.99,N,N,N,N,N
2,HV0003,B03404,B03404,2024-09-01 00:07:08,2024-09-01 00:07:22,2024-09-01 00:08:57,2024-09-01 00:18:34,161,170,1.48,...,1.05,2.75,0.0,0.00,7.62,N,N,N,N,N
3,HV0003,B03404,B03404,2024-09-01 00:19:33,2024-09-01 00:21:14,2024-09-01 00:21:48,2024-09-01 00:46:17,233,220,11.52,...,2.96,2.75,0.0,0.00,29.94,N,N,N,N,N
4,HV0003,B03404,B03404,2024-09-01 00:45:51,2024-09-01 00:49:34,2024-09-01 00:49:34,2024-09-01 01:06:46,220,3,6.29,...,2.53,0.00,0.0,6.38,18.58,N,N,N,N,N

In [5]:
df.columns

Index(['hvfhs_license_num', 'dispatching_base_num', 'originating_base_num',
       'request_datetime', 'on_scene_datetime', 'pickup_datetime',
       'dropoff_datetime', 'PULocationID', 'DOLocationID', 'trip_miles',
       'trip_time', 'base_passenger_fare', 'tolls', 'bcf', 'sales_tax',
       'congestion_surcharge', 'airport_fee', 'tips', 'driver_pay',
       'shared_request_flag', 'shared_match_flag', 'access_a_ride_flag',
       'wav_request_flag', 'wav_match_flag'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19209788 entries, 0 to 19209787
Data columns (total 24 columns):
 #   Column                Dtype
---  ------                -----
 0   hvfhs_license_num     object
 1   dispatching_base_num  object
 2   originating_base_num  object
 3   request_datetime      datetime64[us]
 4   on_scene_datetime     datetime64[us]
 5   pickup_datetime       datetime64[us]
 6   dropoff_datetime      datetime64[us]
 7   PULocationID          int32
 8   DOLocationID          int32
 9   trip_miles            float64
 10  trip_time             int64
 11  base_passenger_fare   float64
 12  tolls                 float64
 13  bcf                   float64
 14  sales_tax             float64
 15  congestion_surcharge  float64
 16  airport_fee           float64
 17  tips                  float64
 18  driver_pay            float64
 19  shared_request_flag   object
 20  shared_match_flag     object
 21  access_a_ride_flag    object
 22  wav_request_flag      object
 23  wav_match_flag        object
dtypes: datetime64[us](4), float64(9), int32(2), int64(1), object(8)
memory usage: 3.3+ GB

In [79]:
# Set primary key for fact_table
df = df.drop_duplicates().reset_index(drop=True)
df['trip_id'] = df.apply(lambda x: uuid.uuid4().hex, axis=1)

In [ ]:
#Create datetime_dim table
datetime_dim = df[['trip_id','request_datetime','on_scene_datetime','pickup_datetime','dropoff_datetime']].reset_index(drop=True)
datetime_dim['request_datetime'] = datetime_dim['request_datetime']
datetime_dim['request_hour'] = datetime_dim['request_datetime'].dt.hour
datetime_dim['request_day'] = datetime_dim['request_datetime'].dt.day
datetime_dim['request_month'] = datetime_dim['request_datetime'].dt.month
datetime_dim['request_year'] = datetime_dim['request_datetime'].dt.year
datetime_dim['request_weekday'] = datetime_dim['request_datetime'].dt.weekday

datetime_dim['on_scene_datetime']= datetime_dim['on_scene_datetime']
datetime_dim['on_scene_hour']=datetime_dim['on_scene_datetime'].dt.hour
datetime_dim['on_scene_day']=datetime_dim['on_scene_datetime'].dt.day
datetime_dim['on_scene_month']=datetime_dim['on_scene_datetime'].dt.month
datetime_dim['on_scene_year']=datetime_dim['on_scene_datetime'].dt.year
datetime_dim['on_scene_weekday']=datetime_dim['on_scene_datetime'].dt.weekday

datetime_dim['pickup_datetime']=datetime_dim['pickup_datetime']
datetime_dim['pickup_hour']=datetime_dim['pickup_datetime'].dt.hour
datetime_dim['pickup_day']=datetime_dim['pickup_datetime'].dt.day
datetime_dim['pickup_month']=datetime_dim['pickup_datetime'].dt.month
datetime_dim['pickup_year']=datetime_dim['pickup_datetime'].dt.year
datetime_dim['pickup_weekday']=datetime_dim['pickup_datetime'].dt.weekday

datetime_dim['dropoff_datetime']=datetime_dim['dropoff_datetime']
datetime_dim['dropoff_hour']=datetime_dim['dropoff_datetime'].dt.hour
datetime_dim['dropoff_day']=datetime_dim['dropoff_datetime'].dt.day
datetime_dim['dropoff_month']=datetime_dim['dropoff_datetime'].dt.month
datetime_dim['dropoff_year']=datetime_dim['dropoff_datetime'].dt.year
datetime_dim['dropoff_weekday']=datetime_dim['dropoff_datetime'].dt.weekday

datetime_dim = datetime_dim[['trip_id','request_datetime','request_hour','request_day','request_month','request_year','request_weekday','on_scene_datetime','on_scene_hour','on_scene_day','on_scene_month','on_scene_year','on_scene_weekday','pickup_datetime','pickup_hour','pickup_day','pickup_month','pickup_year','pickup_weekday','dropoff_datetime','dropoff_hour','dropoff_day','dropoff_month','dropoff_year','dropoff_weekday']]
datetime_dim.head()

#Create hvfhs_license_dim table
hvfhs_licence_code = {
    "HV0002":"Juno",
    "HV0003":"Uber",
    "HV0004":"Via",
    "HV0005":"Lyft"
}

hvfhs_license_dim = df[['hvfhs_license_num']].drop_duplicates().reset_index(drop=True)
hvfhs_license_dim['hvfhs_license_name']=hvfhs_license_dim['hvfhs_license_num'].map(hvfhs_licence_code)

#Create trip_dim table
trip_dim = df[['trip_id','trip_miles','trip_time','PULocationID','DOLocationID']].reset_index(drop=True)

#Create fare_dim table
fare_dim = df[['trip_id','base_passenger_fare','tolls','bcf','sales_tax','congestion_surcharge','airport_fee','tips','driver_pay']].reset_index(drop=True)

In [88]:
#Create fact_table

fact_table = df.merge(trip_dim, on = 'trip_id') \
            .merge(datetime_dim, on='trip_id') \
            .merge(hvfhs_license_dim, on='hvfhs_license_num') \
            .merge(fare_dim, on = 'trip_id') \
            [['trip_id', 'hvfhs_license_num', 'shared_request_flag','shared_match_flag','wav_request_flag','wav_match_flag','access_a_ride_flag','originating_base_num','dispatching_base_num']]

In [89]:
fact_table.head()

,trip_id,hvfhs_license_num,shared_request_flag,shared_match_flag,wav_request_flag,wav_match_flag,access_a_ride_flag,originating_base_num,dispatching_base_num
0,31506131289745aea4f9f9fbbfea61a6,HV0003,Y,N,N,N,N,B03404,B03404
1,15411b59fd1c4161b20f67df603877a1,HV0003,N,N,N,N,N,B03404,B03404
2,71bd5ceb9a714e328bd8ca8cd879f2db,HV0003,N,N,N,N,N,B03404,B03404
3,848aaabb4bb849fb9bf002cc2cf288f1,HV0003,N,N,N,N,N,B03404,B03404
4,3d220b75af3a413f9a26c9171e4d07d3,HV0003,N,N,N,N,N,B03404,B03404